### ISSUE TITLE
self.aft_get_last_transaction = True

### ISSUE THREAD

**Issue by dedalgr** [zacharytomlinson/saspy#28]
Set check_aft_last_transaction = True as parameter.
make self.check_aft_last_transaction = check_aft_last_transaction

Fix:
2784: if self.check_aft_last_transaction:

There are machines that change the transaction number after receiving the signal, but there are also machines that will change the number after responding with Full transfer successful to aft_clean_transaction_poll.
With this option, you are deprived of one check, but you avoid an unexpected error occurring at an inconvenient moment.
Use check_last_transaction=False only for machines that do not change a transaction number

**Comment by well-it-wasnt-me** [comment]
Fixed with your pull request #29

**Comment by dedalgr** [comment]
What is the idea of
I decided to try running the code and it doesn't work. What is meant to be
written here to fix it

match amount:
case 1:
money_1 = money
case 2:
money_2 = money
case 3:
money_3 = money
case _:
raise AFTBadAmount

На нд, 3.03.2024 г. в 1:48 Antonio ***@***.***> написа:
